/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import ticket.booking.entities.Ticket;
import ticket.booking.entities.Train;
import ticket.booking.entities.User;
import ticket.booking.services.UserBookingService;
import ticket.booking.utils.UserServiceUtil;

import java.io.IOException;
import java.util.*;

public class App {
    public static void main(String[] args) {
        System.out.println("Running Train Booking System!");

        Scanner sc = new Scanner(System.in);
        int option = 0;
        UserBookingService userBookingService;
        boolean loggedIn = false;

        try{
//            the first time program runs it loads the DB;
            userBookingService = new UserBookingService();

        }catch (IOException ex){
            System.out.println("There is something wrong");
            return;
        }

        Train trainSelectedForBooking = null;

        while (option != 7){
            System.out.println("Choose Option");
            System.out.println("1. Sign up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Bookings");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a Seat");
            System.out.println("6. Cancel my Booking");
            System.out.println("7. Exit the App");

            if(!sc.hasNextInt()){
                System.out.println("No more input. Exiting the app.");
                break;
            }

            option = sc.nextInt();

            switch (option){
                case 1:
                    System.out.println("Enter your Username");
                    String usernameSignUp = sc.next();
                    System.out.println("Enter your Password");
                    String passwordSignUp = sc.next();
                    User userToSignUp = new User(usernameSignUp, passwordSignUp, UserServiceUtil.hashPassword(passwordSignUp), new ArrayList<>(), UUID.randomUUID().toString());
                    userBookingService.signUp(userToSignUp);
                    break;

                case 2:
                    System.out.println("Enter your Username");
                    String usernameLogin = sc.next();
                    System.out.println("Enter your Password");
                    String passwordLogin = sc.next();
                    User userToLogin = new User(usernameLogin, passwordLogin, UserServiceUtil.hashPassword(passwordLogin), new ArrayList<>(), UUID.randomUUID().toString());

                    try{
//                        Now we have store the user globally;
                        UserBookingService loginService = new UserBookingService(userToLogin);
                        if(loginService.loginUser()){
                            userBookingService = loginService;
                            loggedIn = true;
                            System.out.println("Login successful!");
                        }
                        else{
                            System.out.println("Invalid username or password!");
                        }
                    }
                    catch (IOException ex){
                        return;
                    }

                    break;

                case 3:
                    if(!loggedIn){
                        System.out.println("Please login first!");
                        break;
                    }
                    System.out.println("Fetching Bookings");
                    userBookingService.fetchBooking();
                    break;

                case 4:
                    System.out.println("Enter Source Station");
                    String sourceStation = sc.next();
                    System.out.println("Enter Destination Station");
                    String destinationStation = sc.next();

                    List<Train> trains = userBookingService.getTrains(sourceStation, destinationStation);
                    int idx = 1;
                    for(Train train : trains){
                        System.out.println(idx + "Train Id : " + train.getTrainId());
                        for(Map.Entry<String , String> entry : train.getStationTimes().entrySet()){
                            System.out.println("Station " +  entry.getKey() + " Time: " + entry.getValue());
                        }
                        idx++;
                    }

                    if(trains.isEmpty()){
                        System.out.println("No trains found for the selected route.");
                        break;
                    }

                    System.out.println("Select Train By Typing 1,2,3....");

                    int selectedTrainIndex = sc.nextInt() - 1;
                    if(selectedTrainIndex < 0 || selectedTrainIndex >= trains.size()){
                        System.out.println("Invalid train selection!");
                        break;
                    }

                    trainSelectedForBooking = trains.get(selectedTrainIndex);

                    break;

                case 5:
                    if(!loggedIn){
                        System.out.println("Please login first!");
                        break;
                    }
                    if(trainSelectedForBooking == null){
                        System.out.println("Select A Train First!");
                        break;
                    }

                    System.out.println("Select a seat out of these seats!");
                    List<List<Integer>> seats = userBookingService.fetchSeats(trainSelectedForBooking);
                    for(List<Integer> row : seats){
                        for(int val : row){
                            System.out.print(val + " ");
                        }
                        System.out.println();
                    }

                    System.out.println("Select the seat by typing the row and column!");

                    System.out.println("Enter the row");
                    int row = sc.nextInt();

                    System.out.println("Enter the column");
                    int col = sc.nextInt();

                    System.out.println("Booking your ticket.....");

                    boolean booked = userBookingService.bookTrainTicket(trainSelectedForBooking, row, col);

                    if(booked){
                        System.out.println("Ticket Booked Successfully!");
                    }
                    else{
                        System.out.println("Can't book this ticket!");
                    }
                    break;

                case 6:
                    if(!loggedIn){
                        System.out.println("Please login first!");
                        break;
                    }
                    int calIdx = 1;
                    List<Ticket> bookings = userBookingService.getBookings();
                    if(bookings == null || bookings.isEmpty()){
                        System.out.println("No bookings found.");
                        break;
                    }
                    for(Ticket booking : bookings){
                        System.out.println(calIdx + " " + booking.getTicketInfo());
                        calIdx++;
                    }

                    int bookingIndex = sc.nextInt() - 1;
                    if(bookingIndex < 0 || bookingIndex >= bookings.size()){
                        System.out.println("Invalid booking selection!");
                        break;
                    }

                    boolean status = userBookingService.cancelBooking(bookings.get(bookingIndex).getTicketId());
                    if(status){
                        System.out.println("Ticket Cancelled Successfully!");
                    }
                    else{
                        System.out.println("Can't cancel this ticket!");
                    }

                    break;

                case 7:
                    break;

                default:
                    System.out.println("Invalid Option!");
                    break;

            }
        }
    }
}
